# Outputs to display after terraform apply

output "project_id" {
  description = "Railway project ID"
  value       = railway_project.evolution_backend.id
}

output "project_url" {
  description = "Railway project dashboard URL"
  value       = "https://railway.app/project/${railway_project.evolution_backend.id}"
}

output "backend_url" {
  description = "Backend service URL (will be generated by Railway)"
  value       = "Check Railway dashboard for the generated URL"
}

output "evolution_api_url" {
  description = "Evolution API service URL (will be generated by Railway)"
  value       = "Check Railway dashboard for the generated URL"
}

output "postgres_password" {
  description = "Generated PostgreSQL password"
  value       = random_password.postgres_password.result
  sensitive   = true
}

output "deployment_summary" {
  description = "Deployment summary"
  value = <<-EOT
    ✅ Railway Project Created: ${railway_project.evolution_backend.name}
    ✅ PostgreSQL Database: Deployed
    ✅ Redis Cache: Deployed
    ✅ Backend Service: Deployed
    ✅ Evolution API: Deployed
    
    🔗 Dashboard: https://railway.app/project/${railway_project.evolution_backend.id}
    
    Next steps:
    1. Visit the Railway dashboard to get service URLs
    2. Configure your domain (if needed)
    3. Monitor deployment logs
  EOT
}
